theme: jekyll-theme-minimal
title:  Mechanical and Hydrodynamic Analyses of Helical Strake-like Ridges in a Glass Sponge
description: MATHEUS C. FERNANDES, MEHDI SAADAT, PATRICK CAUCHY-DUBOIS, CHIKARA INAMURA, TED SIROTA, GARRETT MILLIRON, HOSSEIN HAJ-HARIRI, KATIA BERTOLDI, AND JAMES C. WEAVER
google_analytics: []