theme: jekyll-theme-minimal
title: Mechanical and Hydrodynamic Analyses of Helical Strakes in the Skeletons of Glass Sponges
description: This contains the data and code for the publication in the Journal of Royal Society Interface.
google_analytics: []