theme: jekyll-theme-minimal
title:  Mechanical and Hydrodynamic Analyses of Helical Strake-like Ridges in a Glass Sponge
description: Matheus C. Fernandes, Mehdi Saadat, Patrick Cauchy-Dubois, Chikara Inamura, Ted Sirota, Garrett Milliron, Hossein Haj-Hariri, Katia Bertoldi, and James C. Weaver (jweaver@seas.harvard.edu)
google_analytics: []