theme: jekyll-theme-minimal
title:  Mechanical and Hydrodynamic Analyses of Helical Strake-like Ridges in a Glass Sponge
description: This contains the data and code for the publication in the Journal of Royal Society Interface.
google_analytics: []